### ISSUE TITLE
Calculation Group that causes measure data types to decay to Variant is not picked up by Tabular Editor 3

### ISSUE THREAD

**Issue by atmisra** [TabularEditor/TabularEditor3#111]
For the same action of adding a calculated table and saving the changes back to the database, Tabular Editor 2 displays an error that is not shown in Tabular Editor 3 (same model and action).
Model is in Power BI premium, accessed with XMLA read/write. Actual error encountered related to a variant data type, resulting from a measure fed by a calculation group.

![tabular editor issue](https://user-images.githubusercontent.com/80759879/123843323-caffcb00-d8df-11eb-9484-c87fb6b0909f.PNG)

**Comment by otykier** [comment]
Thanks for reporting. Tabular Editor currently doesn't detect the measure data type decay, which may sometimes happen when a calculation group is added to the model (depending on the complexity of the calculation item logic). Thus, Tabular Editor "thinks" that all measures have well-defined data types (Int, String, Double, etc.), where in reality Analysis Services would decay all measures to the Variant data type. This prevents the measure from being used in an expression that turns into a column (since columns can not have the Variant data type). You can use the [DAX CONVERT](https://dax.guide/convert/) function to convert the measure to a specific data type before using it in a column expression.

I will look into having Tabular Editor 3 detect the data type decay based on calculation item formulas, but it's not a trivial task and other issues have higher priority currently.

**Comment by atmisra** [comment]
Thank you Daniel,
I love your product and look forward to your continued investment in it. Also, I give credit to the ElegantBI.com blog for promoting some edge use cases I have found very useful.
I just sent a message earlier to your licensing team around extending my trial license while EY procurement/legal work get your company added as an approved vendor. If there’s anything you can do to allow for this, I appreciate it. Regardless, I’ll be a customer.

-Arun, EY

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
