### ISSUE TITLE
Add "define measure" option like in dax studio

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#117]
**Is your feature request related to a problem? Please describe.**
When writting a DAX query is not easy to test a modification of a measure

**Describe the solution you'd like**
I'd like add the define statement of a measure, like in DAX studio

**Describe alternatives you've considered**
You can always copy & paste, but that's not super cool

**Comment by otykier** [comment]
This feature has existed for a while now:

![image](https://user-images.githubusercontent.com/8976200/124008671-f6b4ab00-d9dc-11eb-9ba0-582ffe2d227c.png)

Did you expect the "Define Measure" command to be available through some other means?

**Comment by bernatagulloesbrina** [comment]
I expressed myself poorly

I mean define measure but taking an existing measure as base, like you do
in dax studio

For the query it will use the modified definition but no changes are made
to the model

**Comment by otykier** [comment]
@bernatagulloesbrina maybe I'm misunderstanding, but this is exactly what happens when you click on the "Define Measure" option in the screenshot above. Once you have a bunch of MEASURE definitions at the top of the script, you can copy those and paste them as a DAX Script, if you want these definitions applied to your local model:

![definemeasure](https://user-images.githubusercontent.com/8976200/124019632-92e4af00-d9e9-11eb-80cf-1c5b6f293baa.gif)

**Comment by bernatagulloesbrina** [comment]
Just saw it on Twitter first! Thank you, I wasn't aware this works like
this. I was looking in the right click menu over a measure, but this is way
way better
