### ISSUE TITLE
Messages window doesn't update if unprocessed tables get processed

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1204]
### Description

I like the new feature in 3.13 that alerts you in the Message window if a table is in an unprocessed or uncalculated state, but once it is processed or calculated, the message won't go away. Only way I have been able to clear it is to close/reopen TE/3.

### Tabular Editor 3 Version

3.13

### Steps to Reproduce

1. Open model with unprocessed or uncalculated table (in the service, not PBIX)
2. Refresh the table, or recalc the table/model for calculated items
3. Message remains after the refresh is done

### Expected behavior

Messages go away

### Windows Version

10

**Comment by otykier** [comment]
This is by design, but we probably need to make this more clear somehow.

The warning message should indicate that you need to save/reopen the model to have the message go away. The reason for this is that we can’t know the actual state of the object until we update the local model metadata from the AS instance, and this would override any local changes that had not yet been saved to the AS instance. Moreover, an object could have its state changed if a refresh was performed outside of Tabular Editor, so in general we can’t know what the state currently is - we only know the state from the last time the model metadata was updated (that is, the last time the model was saved or opened in Tabular Editor).

**Comment by edhans** [comment]
Ahhh... yes. Saving the model clears it. Thanks!
