### ISSUE TITLE
SSL Connection Error - Cannot Connect to Server

### ISSUE THREAD

**Issue by ry-guy5** [TabularEditor/TabularEditor3#1242]
### Description

Trying to connect to Power BI XMLA endpoint and receiving SSL connection error message. Seemed to start after Windows 11 upgrade. 

### Tabular Editor 3 Version

3.14.0

### Screenshots

![TE3 SSL Error](https://github.com/TabularEditor/TabularEditor3/assets/79316827/4bf2af34-14e7-4495-9cfe-fb3860eade9c)

### Steps to Reproduce

1. Go to 'Open model from DB'
2. Enter Power BI Service Workspace XMLA endpoint in Server field
3. Click ok
4. SSL error occurs

### Expected behavior

I should be able to connect to the model in the PBI Service. 

### Windows Version

Windows 11 (Version: 22H2)

**Comment by otykier** [comment]
We're not aware of any general issue after upgrading Windows 11.

I wonder if perhaps a firewall, VPN or Proxy could be interfering with your connection? Have you tried connecting to the XMLA endpoint using other tools, such as SQL Server Management Studio or DAX Studio? Also - if you're able to test this from more than one machine, that would also be helpful.

Also, if you could send us your Session ID (**Help > About Tabular Editor**) from one session where you've experienced this error, we may be able to locate the exact error details in our telemetry, for that particular session.

**Comment by ry-guy5** [comment]
Interesting! TE2 (2.18.1) connects just fine, but DAX Studio (3.0.5) will not connect. Screenshot attached.

![DAX Studio Connection Error](https://github.com/TabularEditor/TabularEditor3/assets/79316827/9fd74320-0cd7-4373-97a8-8359d95c4851)

Are there any connection settings in TE3 I can adjust?

TE3 Session ID: 452c6c44-7641-4373-80c7-a3dfdb009b8f

**Comment by otykier** [comment]
You can try to change the proxy options under **Tools > Preferences > Proxy settings** (restart the application after making a change here), but that’s about it, I’m afraid.
There may also be some [XMLA connection string](https://learn.microsoft.com/en-us/analysis-services/instances/connection-string-properties-analysis-services?view=asallproducts-allversions) options you can explore, but I’m not aware of any that would impact SSL.

TE 2.18 uses an older version of the AMO/TOM client libraries that Tabular Editor uses to connect, so perhaps it’s a regression of this library (which is owned by Microsoft). Could you try to compare with an older version of TE3, for example [3.8.0](https://docs.tabulareditor.com/te3/other/release-notes/3_8_0.html?tabs=downloads)? Not sure about DAX Studio, but they use ADOMD instead of TOM.

**Comment by ry-guy5** [comment]
Tried TE3 3.8.0 and still experiencing SSL issue. Explored XMLA connection options...no luck. 

![TE3 3 8 Error](https://github.com/TabularEditor/TabularEditor3/assets/79316827/f4d7d486-d6f2-47d4-84c0-64f8a1f57a9e)

Will need to dig into proxy settings with IT. Will report findings.

**Comment by ry-guy5** [comment]
**FIX FOUND**
Resolution: TPM version was out of date and Group Policy was not updating correctly. Not a TE3 issue, rather an internal issue.

**Comment by DBojsen** [comment]
Hi @ry-guy5 

Great that you resolved your issue, and thank you for pasting the solution her for visibility to others.
I'll close the issue.

Best Regards

David - TE3 Support
