### ISSUE TITLE
Refresh table in dataset problem- table added from BigQuery 

### ISSUE THREAD

**Issue by vladatbint** [TabularEditor/TabularEditor3#1301]
### Description

We have BQ as our DB/DWH and we have one big data set (~30GB) in our PBI service as our main dataset.
We use the ODBC connector in TE3 to connect to BQ, 
When we added a table to the model we had the following situations:
1) when trying to refresh data in TE3 in order to preview data we got the error 
2) when we deploy changes, the model crashes in PBI service and can not be refreshed any more, we have to remove table which we added
3) why tables which are added through TE3 have different table in PBI service 

Please for help for adding a table, this is one of crucial things for us.
Thank You

### Tabular Editor 3 Version

3.15

### Screenshots

1)  **when trying to refresh data in TE3 in order to preview data we got the error** 
![image](https://github.com/TabularEditor/TabularEditor3/assets/169165993/1daea5cc-026f-453c-be54-9b2555a2b038)
2) **when we deploy changes, the model crashes in PBI service and can not be refreshed any more, we have to remove table which we added**
![image](https://github.com/TabularEditor/TabularEditor3/assets/169165993/3076e1fd-8847-4f15-ad4e-fb963ad986c7)

3) **why tables which are added through TE3 have different table in PBI service** 
![image](https://github.com/TabularEditor/TabularEditor3/assets/169165993/2b780cdd-e8b9-4714-9d77-f0b03fcb75a0)

### Windows Version

W10

**Comment by vladatbint** [comment]
Hi,
in the meantime, we solved a problem in another way.
- make a new Data table
- delete the default portion
- make a new M partition 
- put standard M code
- some small settings in the properties part regarding anotation etc.

and it works.

Only point 3), regarding icons we can not figure out , why icon is a measure table.

Thanks

**Comment by mlonsk** [comment]
Hi @vladatbint 
It sounds like from the error messages you receive  is due to the ODBC connector. Power BI works primarily through so called implicit data sources which is what you are creating when making new partitions with M code. 
And the best work around there is, as you do, take standard M code generated by Power BI Desktop to fill into your partition. 

To the third point. The reason for the icon change is that the Power BI service treat tables where only measures are visible as "measure tables" and these have a separate icon in the service. In Tabular Editor 3 we consider everything to be tables regardless of what is visible to the end user.
