### ISSUE TITLE
Cannot import table or update schema against Oracle Database

### ISSUE THREAD

**Issue by JoBuGD** [TabularEditor/TabularEditor3#1312]
### Description

HI,

We are trying to import some tables from an old Oracle Database (11g).
Everything works fine until we select the table for preview. The same error occurs when we are trying to update the table schema (on a working model build outside of Tabular Editor).

### Tabular Editor 3 Version

3.15.0.23506

### Screenshots

![2024-05-30 10_49_59-Import tables](https://github.com/TabularEditor/TabularEditor3/assets/172390746/43d5936b-b9a9-476e-a35e-c6791cce58d0)
![2024-05-30 10_50_48-dubreuildsiazaspbi01ne PTP - PAG Achats (Import) - Tabular Editor 3 15 0 - Enter](https://github.com/TabularEditor/TabularEditor3/assets/172390746/41f5fc54-6a3b-4f9f-98da-4befcd3152e0)

### Windows Version

Windows 11

**Comment by mlonsk** [comment]
Hi @JoBuGD 

Thank you for reporting this. This looks like a bug, but we will have to take a closer look before confirming.

Could you answer a few questions about your connection to Oracle? 
(If you don't want to answer in a public forum, you can also write to support@tabulareditor.com)

Are you using an Analysis Service model or Power BI model?
What kind of data source do you use? (First page of Import wizard: Legacy, structured or implicit)
Are you connecting through the Oracle connector, and if so, which driver do you use?
Could you send us a few extra screenshots of how you establish the connection to Oracle through the import wizard?

**Comment by JoBuGD** [comment]
Here are the answers :
- We are using an Analysis Services Model
- using a structured data source
- through the Oracle connector (12.2.0.1.0) : both 32bits and 64bits versions are installed for ... ... reasons

Screenshots from the previsous sreps of the import wizard
![2024-06-13 14_11_55-dubreuildsiazaspbi01ne PTP - PAG Achats_ (Import) - Tabular Editor 3 - Enterpris](https://github.com/TabularEditor/TabularEditor3/assets/172390746/6d08c687-cd26-42e9-a595-3b6cb5432c2e)
![2024-06-13 14_12_11-dubreuildsiazaspbi01ne PTP - PAG Achats_ (Import) - Tabular Editor 3 - Enterpris](https://github.com/TabularEditor/TabularEditor3/assets/172390746/5d4ebb6f-9613-4f3f-8289-8638e49ac524)

**Comment by mlonsk** [comment]
Hi @JoBuGD 

Thank you for the answers! We will look into it.

A thing you could try is to set the 'Additional connection string properties' to "uid=username;pwd=password"

**Comment by otykier** [comment]
Hi @JoBuGD 
Thank you for patience while we investigated this issue. The main issue is that Oracle 11g does not support all of the OLE DB / ANSI SQL that Tabular Editor 3 uses to query the database for table preview and schema information.

Specifically, for the table preview, TE3 uses a SQL query that looks like: `SELECT * FROM Table FETCH FIRST 100 ROWS ONLY`. The row limiting part of this query is not supported on Oracle 11g.

But more important, when TE3 needs to query the schema information (column names and datatypes), it uses an OLE DB method called `GetSchemaTable`. The OLE DB driver then generates a query which references the IDENTITY_COLUMN, so it would seem that this is also incompatible with Oracle 11g (since IDENTITY was only [introduced in Oracle 12c](https://forums.oracle.com/ords/r/apexds/community/q?question=does-identity-feature-available-in-oracle-11g-1844)).

Considering that Oracle 11g went out of extended support 4 years ago, I'm afraid this is not a scenario that we will address. Maybe you can workaround the issue by using an older set of OLE DB drivers (if you can find such), or perhaps you could work around the issue using Visual Studio / Power Query to perform the initial import of tables?

So for now, I'll close this ticket but feel free to comment if you have any additional questions.
