### ISSUE TITLE
Debug not available - caused by format strings?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1377]
### Description

I was running a fairly simple query and when trying to use the debugger, it was unavailable. I deleted the format string part of the query:
IGNORE('Table'[Measure Name FormatString])

And then I was able to debug. Is this a known issue, just a fluke with this query? The FSE is very simple but it does use SELECTEDMEASURE() as I need to blank out the FSE if the measure returns blank.

Does it thing a Calc Group is in play?

### Tabular Editor 3 Version

3.17.0

### Windows Version

11

**Comment by otykier** [comment]
Confirmed as a bug. I think the issue here, is that our semantic analyzer thinks that the reference to the FormatString in the DAX is an error:

![image](https://github.com/user-attachments/assets/21d11d69-3593-4f35-ac26-bddfd859721e)

Unfortunately, the debugger won't work if the semantic analyzer thinks there's an error in the code. We'll look into it.

**Comment by mlonsk** [comment]
Hi @edhans 

The FormatString issue has been solved in the latest version of Tabular Editor 3 (3.18.0), and the debugger should now be able to be used while these are present in the query. Debugging the FormatString itself is, however, still not possible. 

Thank you for reporting it.
