### ISSUE TITLE
How do you update IsAvailableInMDX

### ISSUE THREAD

**Issue by chrisumphlett** [TabularEditor/TabularEditor3#138]
I am learning how to use the Best Practice Analyzer. I want to update IsAvailableInMDX per https://blog.crossjoin.co.uk/2018/07/02/isavailableinmdx-ssas-tabular/. This article shows screenshots from TE 2.6 with an "Other" section when looking at a column's properties, which does not appear for me in Tabular Editor 3.0 (or in 2.16). I started a trial for 3.0 hoping it would reveal this and I would likely subscribe for this feature alone if it creates the time savings that are mentioned in that article.

**Comment by otykier** [comment]
Are you working against a Power BI Desktop model? Please be aware that [Power BI Desktop does not support column modifications made from external tools](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations), and for this reason, Tabular Editor (both 2 and 3) blocks the unallowed operations and hides certain properties by default.

However, you can override this behavior under Tools > Preferences > Power BI > Allow unsupported modelling operations, but since this could potentially break your .pbix file, please make sure to keep a backup of the file, just in case.

**Comment by chrisumphlett** [comment]
Got it. That's what I needed to know. The properties still don't show the same thing per that screen shot, but I was able to use the "apply fix" command now which explains why that hadn't been working before.
