### ISSUE TITLE
Model.AllMeasures.FormatDax(); is timing out

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#148]
I have a script that creates some very long DAX measures (over 5k lines each). When I call the Model.AllMeasures.FormatDax(); function at the end of my c# routine and it timesout . Is there a way to call the FormatDax method for a specific measure so that I can call it for each long DAX measure I am creating? Or is there a way to increase the timeout period ?

**Comment by marcosqlbi** [comment]
This is quite strange. I don't see errors on the service side (in the last few days). 
You can find the documentation here: 
https://docs.tabulareditor.com/FormatDax.html

You can try to manually iterate the measures, but keep in mind that multiple measures are merged into a single request and sent together to the service in order to optimize the performance. Therefore, you should try to run a script that excludes measures rather than just looping over all the measures in an explicit way, because the latter wouldn't change the way the DAX code is sent to the service.

Please, let me know if you can identify the issue. If you can share (also privately) the BIM file, I would like to take a look to the issue because I want to make sure we don't have a problem on the service side.

Thanks!

**Comment by dpesante** [comment]
@marcosqlbi Let me put something together that hides any proprietary info and go from there. or if you would like for me to try it at a specific time.. let me know...

**Comment by marcosqlbi** [comment]
If you can create a repro it is better - if we don't have errors server side it's hard to diagnose the problem (we don't capture the syntax processed by the server).

**Comment by dpesante** [comment]
@marcosqlbi working on getting you the BIM file. Just need to remove anything that related to PII data, etc. Hopefully by EOW.

**Comment by otykier** [comment]
Closing this, as offline formatting has been available since 3.1.6.
