### ISSUE TITLE
Question: Allow multi-paste under Text Editors

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#170]
I am curious to know what this option is supposed to do?

![image](https://user-images.githubusercontent.com/73054674/128826659-00c513cf-bd3d-4e36-9d74-f2e0621fd9c8.png)

**Comment by otykier** [comment]
When this is checked, text will be pasted into all selections instead of the main selection only. To illustrate:

Without multi-paste:
![no-multipaste](https://user-images.githubusercontent.com/8976200/128829404-0206cc46-f993-488d-8ef4-875b89325d80.gif)

With multi-paste:
![multipaste](https://user-images.githubusercontent.com/8976200/128829369-d2a1e12e-4be1-419d-8e38-a887f7e3483f.gif)

We'll make sure to add a tooltip to this option to explain the difference.

**Comment by SharmaAntriksh** [comment]
Thanks!! Please feel free to close or keep this open.

**Comment by otykier** [comment]
Tooltip added in [3.0.10](https://github.com/TabularEditor/TabularEditor3/releases/latest).
