### ISSUE TITLE
Problem with RETURN statement

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#19]
Before the RETURN part the virual columns created are accessible throughout the code but after RETURN keyword some of them aren't accessible.

Before RETURN keyword:
![image](https://user-images.githubusercontent.com/73054674/120337588-12129480-c311-11eb-87ef-d2af61e0f874.png)

After RETURN keyword:
![image](https://user-images.githubusercontent.com/73054674/120337611-1939a280-c311-11eb-9f86-f3cd3b51b8c5.png)

But missing columns re-appear after using MINX
![image](https://user-images.githubusercontent.com/73054674/120338339-c4e2f280-c311-11eb-9edd-fd3c407ecfb1.png)

If instead of Measure reference in the "[@Sales Amount]" column I use the expanded code the column shows up 
![image](https://user-images.githubusercontent.com/73054674/120339252-93b6f200-c312-11eb-999e-e0c32625739a.png)

CONCATENATEX doesn't appear in the IntelliSense 
![image](https://user-images.githubusercontent.com/73054674/120338421-d88e5900-c311-11eb-8f6f-66132dabc83c.png)

but after using table contructor it is accessible:
![image](https://user-images.githubusercontent.com/73054674/120338496-e8a63880-c311-11eb-9447-ec3b69f0e480.png)

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.

Please note that Tabular Editor's autocomplete does not suggest measures if their data type doesn't match what is expected in the current function: So for the 2nd argument of SUMX, only numerical values are valid, so if you have a measure that returns a String, that measure will not be suggested.
