### ISSUE TITLE
Installer doesn't set "Start In" on shortcuts

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#192]
On the face of it this wouldn't be an issue, however, I've tried calling the Microsoft.AnalysisServices.Core.dll in an advanced script only to get the error "Metadata file 'Microsoft.AnalysisServices.Core.dll' could not be found". Once the "Start In" is set on the desktop / start menu shortcut I no longer receive this error.

(This had me scratching my head for a while... 😵 )

![image](https://user-images.githubusercontent.com/62320770/130590107-279fcb07-fe83-403a-921b-1a6c80548375.png)

**Comment by samaguire** [comment]
Additionally, this also kills the loading of macros as right click actions.

[MacroActionsError.log](https://github.com/TabularEditor/TabularEditor3/files/7038228/MacroActionsError.log)

**Comment by otykier** [comment]
Starting from 3.1.1 (to be released later this week), Tabular Editor now looks for DLL's in the installation directory, if the path of the DLL is not fully specified in the `#r` statement within the script. The "Start in" property of the shortcut has not been changed (since that has other consequences).

**Comment by otykier** [comment]
[3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html) is now released. Thanks for reporting!
