### ISSUE TITLE
Diagram canvas -> relationship context menu -> should have Delete Relationship option...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#195]
And Del key should also delete it. :)

**Comment by otykier** [comment]
There should definitely be a right-click option for deleting a relationship within the diagram view, but I'm not sure if the [Del] key should map to this by default. The reason is that [Del] is already a shortcut for removing a table from a diagram (not deleting the table from the model). So this would introduce an inconsistency in the diagram view which I think could cause some confusion.

Perhaps it would be better to enable double-clicking on an object in the diagram (table, column or relationship), to move the focus over to the TOM Explorer. Once the TOM Explorer is focused, hitting the [Del] key causes the selected object to be deleted from the model.

Thoughts?

**Comment by seedjay1** [comment]
1) Right-click delete option suffices, if that's the most that can be unambiguously done.
2) I personally hate the TOM explorer for relationships, because there's so many of them, with so much of the text name the same, etc. I immediately get lost there and close it up :)
3) In my imagination, the Del key would be delete for *whatever diagram object* has focus - table, column, relationship, whatever. That seems like a consistent experience to me - what am I missing? Include an "are you sure?" dialog if wanted.

**Comment by otykier** [comment]
Please see #139. In general, I think the most intuitive behavior of the Del key, while in the Diagram View, is to remove the table from the diagram only (but keep the table in the model).

In addition to a right-click option for deleting the relationships, I'm willing to show a prompt when hitting Del while a relationship is selected in the diagram, with a text like: "You cannot remove relationships from a diagram. Do you want to delete this relationship from the model? [OK/Cancel]".

**Comment by seedjay1** [comment]
Aaah yes I see your point now - tables differ from relationships in that they can't reasonably be deleted *from the diagram*. Whereas tables can be meaningfully deleted from *either* the diagram or the model. 

I think your compromise is just fine!

**Comment by otykier** [comment]
Remove relationship option added in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0).
