### ISSUE TITLE
Some functions aren't accessible in the IntelliSense 

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#20]
While creating Query Measures some of the functions are only available inside table contructors: Those functions are DISTINCTCOUNTNOBLANK, CONCATENATEX, DISTINCTCOUNT, BLANK, CONCATENATE etc

https://user-images.githubusercontent.com/73054674/120340288-7f272980-c313-11eb-9ec0-a9826b50dc6f.mp4

FILTER
![image](https://user-images.githubusercontent.com/73054674/120345522-2c03a580-c318-11eb-8b04-6e3d8525cc56.png)

EARLIER
![image](https://user-images.githubusercontent.com/73054674/120345649-4b023780-c318-11eb-9a09-513fad5ddee4.png)

**Comment by otykier** [comment]
Your first example is a bug, related to #19. It will be fixed in 3.0.3 to be released shortly.

Your example with FILTER is by design, since the 2nd argument of SUMX should be a scalar value, and FILTER is generally used to return a table of values.

EARLIER is not shown since it is not recommended to use this function (use variables instead). However, if you want the auto complete to show not recommended/deprecated functions, you can enable this under Tools > Preferences > DAX Editor > Code Assist > "Show deprecated / not recommended DAX functions"

**Comment by otykier** [comment]
Your first example is now fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
