### ISSUE TITLE
Data source password is overwritten/removed from workspaceDB

### ISSUE THREAD

**Issue by helgews** [TabularEditor/TabularEditor3#205]
In testing how we could use TE3 in our workflow, I set our AzureAS-model in the DEV-environment (loaded with production data) as my workspace DB. Nice things: preview data, pivot grid, testing dax, vertipaq (please include option for more vertipaq-information - see #190 ).

One issue that has arisen, is that our data source password keeps getting removed from the model. The password was never touched before, when we developed in TE2. So this is a side-effect of setting is as my workspace DB?

Maybe I am going about this the wrong way. I opted out of having a "personal" workspace DB in order to save capacity (developing on S0/S1) and not having to refresh tables with data by myself.

Edit: Could it be related to me entering the data source (sql) password in order to import table or refresh metadata, and then this is considered a change on the data source item? (which in turn is saved to workspace db with password omitted)

**Comment by otykier** [comment]
The way the workspace mode works, is that when you open a Model.bim file that has been configured to use a workspace database (these settings are stored in the Model.UserName.tmuo file next to the Model.bim file), Tabular Editor immediately deploys the contents of the .bim file to the workspace database. If any data sources in the model require credentials, Tabular Editor should prompt you to enter these credentials the first time the workspace database is deployed. In addition, the credentials are encrypted and stored in the .tmuo file, so that they can be applied automatically the next time the file is loaded.

In any case, during deployment of the workspace database when the Model.bim file is loaded, any credentials on the server are overwritten with those in the Model.bim file or those in the .tmuo file.

With TE2, you likely loaded the metadata directly from the deployed database, in which case the password was never touched, but since we have to treat the Model.bim file as the "source of truth", we have to perform an initial deployment when using the workspace mode.

In your case, it sounds like Tabular Editor doesn't recognize that one or more data sources in the Model.bim file requires credentials, so you didn't get the prompt for some reason.

To better debug the issue, could you provide more information on the data source(s) used in your model? Ideally, if you could sent a stripped down Model.bim file to daniel@tabulareditor.com with just the data sources (blank out any credentials and server/database names with XXXXX before sending), or paste their JSON definition here. Thanks!

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). Thanks for reporting!
