### ISSUE TITLE
Perspectives - adding a measure to a table already in a perspective does not add the new measure to perspective

### ISSUE THREAD

**Issue by albegouws** [TabularEditor/TabularEditor3#216]
When adding a new measure to a table that is already included in a perspective that measure is not included in the perspective.  

To workaround the measure needs to added to the perspective, or the table needs to be removed from the perspective and re-added. 

Ideally any added columns or measures should inherit the perspective membership from the table.

**Comment by otykier** [comment]
I think the best way to solve this would be to add two new options (**unchecked** by default):

- [ ] Inherit perspective membership when new objects are created on a table
- [ ] Inherit perspective membership when pasting/moving objects to a table
   
I don't want to change the default behavior since it works the same way in TE2 and it has worked that way for several years, but the above options could be used if you prefer measures/columns/hierarchies to inherit the table perspective information by default.

While we're add it, let's also add this as an option (default would be **checked** to have the same behavior as today):

- [X] When a table is added to a perspective, also add all child objects to that perspective

Thoughts?

**Comment by albegouws** [comment]
Those first two options sounds perfect, although the additional child
option (3rd option) can be read as enabling inheritance as well?

**Comment by otykier** [comment]
This is fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html). You can find the new options under **Tools > Preferences > Modeling Operations**. Thanks for reporting!
