### ISSUE TITLE
Save to Folder only outputs Database.json

### ISSUE THREAD

**Issue by JelleScheper** [TabularEditor/TabularEditor3#221]
After trying all possible options for saving to folder, only database.json is actually saved to the chosen folder

This is happening in version 3.1.0

Could anyone point me in the right direction of a solution?

**Comment by otykier** [comment]
Hi @JelleScheper 
Please review your settings under **Tools > Preferences > File Formats > Save-to-folder**. You should either ensure that "Use recommended settings" is checked, or alternatively, make sure that the objects you want serialized into individual files are checked under "Serialization depth".

![image](https://user-images.githubusercontent.com/8976200/133390732-788b6f80-660a-45c4-9704-a8bda42ddafd.png)

In addition, the first time you save the file as a folder, you should **uncheck** "Use serialization settings from annotations", since your model might previously have been saved with serialization settings that prevents objects from being serialized as individual files:

![image](https://user-images.githubusercontent.com/8976200/133391000-3e68478c-1101-4dbf-ae3b-1a49f1bcf4a7.png)

**Comment by JelleScheper** [comment]
After trying this, with the exact settings as above, I still only get a Database.json file.
Could this be the result of connecting to an Analysis Services Model and then trying to save to folder?

**Comment by JelleScheper** [comment]
Turns out my save to folder settings could have been conflicting with a previous installation of a tabular editor 2.x installation.

After uninstalling the 2.x version of tabular and restarting Tabular editor 3 the problem was solved.

Thanks for your time
