### ISSUE TITLE
Small complaint: Pivot Grid headings difficult to read using "Dark" theme

### ISSUE THREAD

**Issue by ebeery11** [TabularEditor/TabularEditor3#287]
Currently, the Pivot Grid headings ("Drop Filter Fields Here", "Drop Data Items Here", etc.) are a little difficult to read when using "Dark" theme, especially on a screen with high glare.  Could that text be lightened slightly in a future release? 

Also want to just say that I really appreciate having the Dark theme, and this is the only instance so far where I've seen any issues at all with contrast/readability!!

**"Basic" Theme**
![image](https://user-images.githubusercontent.com/16659917/140523262-0a6cb48f-9e6f-43f0-91b9-bcd8e53a7d8b.png)

**"Dark" Theme**
![image](https://user-images.githubusercontent.com/16659917/140523074-447bac53-639e-4fd7-a592-6bc298be1814.png)

**Comment by otykier** [comment]
Instead of using the "Dark" theme, try to use the "Basic" theme with the "Blue Dark" palette:

![image](https://user-images.githubusercontent.com/8976200/140749852-6548a4bf-1534-409b-9cc8-257077587a57.png)

In a future update, the "Blue", "Dark" and "Light" themes will be removed, as these are raster-based themes. The application generally looks better using "Basic" or "Bezier", since these are vector-based, and both have many different palettes to choose from.

**Comment by ebeery11** [comment]
Wow nice!! Didn't even know that was an option...  This one can be closed then as far as I'm concerned, thanks for the help @otykier !
