### ISSUE TITLE
Unable to create a new table in the model.

### ISSUE THREAD

**Issue by CraigsterT** [TabularEditor/TabularEditor3#288]
Hi Daniel 

I've just started to receive the error message below when trying to create a new table in the Contoso dataset. Worked fine a few days ago .

![image](https://user-images.githubusercontent.com/66374274/140640279-81175484-6bb8-4c13-869f-21bb72c3b1ca.png)

**Comment by otykier** [comment]
This error typically occurs when you try to add a table with an M partition where no M expression is specified.

**Comment by CraigsterT** [comment]
Thanks Daniel - The process that I am following is a basic Alt + 5
operation so I don't think, at this stage, that I am touching anything to
do with M code although admittedly the error message would lead you to
believe that. As stated, worked fine the other day but not now.

**Comment by otykier** [comment]
@CraigsterT ALT+5 adds a new table to the model. Since all tables must have at least 1 partition, Tabular Editor simultaneously adds a partition to the newly created table. There is some logic that determines the type of partition created (SQL vs M) based on the other partitions and types of data sources in the model. Maybe the table you added the last time had a SQL partition rather than an M partition, or maybe the M expression was specified before you saved? Analysis Services will not accept a model that contains a table with an empty M partition, where as an empty SQL partition is ok (although you will get an error when trying to refresh such a table).

**Comment by otykier** [comment]
Closing this, but feel free to comment if you have any further questions.
