### ISSUE TITLE
Find and replace over Annotations does not reveal results from partitions

### ISSUE THREAD

**Issue by atmisra** [TabularEditor/TabularEditor3#299]
I have a model with the same annotation on certain tables and certain partitions. The "Find Results" initiated from the "Find and Replace" dialog box only reveals results from the tables.

**Comment by otykier** [comment]
This was fixed in October 2022 - "Find Results" will search both annotation names and values when checked:

![image](https://user-images.githubusercontent.com/8976200/217538630-352b556a-58ce-41db-9744-bd9dd7f0dc7c.png)

Apologies for the missed communication. You can find the latest update here: https://docs.tabulareditor.com/te3/other/downloads.html
