### ISSUE TITLE
`CallDaxFormatter()` isn't respecting short/long line option

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#324]
`CallDaxFormatter()` is only formatting as long lines when using the internal formatter despite my options/preferences being set to short lines 😪

(Interim workaround is to set line limit for long lines to be the same as short lines...)

Otherwise working well ☺

![image](https://user-images.githubusercontent.com/62320770/146490497-21a5ea24-aa32-4ad6-86bb-07569c86408a.png)

![image](https://user-images.githubusercontent.com/62320770/146490664-79254bf8-8178-428f-a8a4-86a7cd3da9b6.png)

_Originally posted by @samaguire in https://github.com/TabularEditor/TabularEditor3/issues/307#issuecomment-996438246_

**Comment by otykier** [comment]
@dybzon could you investigate?

**Comment by dybzon** [comment]
@samaguire which script are you running here? Is it the same one [that you posted previously](https://gist.github.com/samaguire/e8f60ea57e967070a5325559ae245f9d)?

**Comment by dybzon** [comment]
@samaguire The signature of the CallDaxFormatter() method is this:

`CallDaxFormatter(bool shortFormat = false, bool? skipSpaceAfterFunctionName = null)`

The issue here is that the default value for `shortFormat` is `false`. You can fix this by explicitly specifying the `shortFormat` value: `CallDaxFormatter(true);`.

I understand that you were expecting the method to pick up the value from configuration per default, is that correct? I also feel that would make sense.

@otykier What do you say we change the signature to
`CallDaxFormatter(bool? shortFormat = null, bool? skipSpaceAfterFunctionName = null)`
and default to the user's configuration value rather than defaulting to false?

**Comment by samaguire** [comment]
> @samaguire which script are you running here? Is it the same one [that you posted previously](https://gist.github.com/samaguire/e8f60ea57e967070a5325559ae245f9d)?

Yes. (Though it now includes a couple of tweaks given your previous suggestions.)

**Comment by samaguire** [comment]
> @samaguire The signature of the CallDaxFormatter() method is this:
> 
> `CallDaxFormatter(bool shortFormat = false, bool? skipSpaceAfterFunctionName = null)`
> 
> The issue here is that the default value for `shortFormat` is `false`. You can fix this by explicitly specifying the `shortFormat` value: `CallDaxFormatter(true);`.
> 
> I understand that you were expecting the method to pick up the value from configuration per default, is that correct? I also feel that would make sense.
> 
> @otykier What do you say we change the signature to `CallDaxFormatter(bool? shortFormat = null, bool? skipSpaceAfterFunctionName = null)` and default to the user's configuration value rather than defaulting to false?

Yes I was expecting it to pickup settings from config rather than a default of false.

Your suggested change would be ideal. 😁

I wasn't aware of the signature, so will specify this in the script in the interim.

**Comment by otykier** [comment]
@dybzon great idea - go ahead :-)

**Comment by dybzon** [comment]
This will be fixed in the next release (3.1.8). Thanks for your input @samaguire.

**Comment by otykier** [comment]
Fixed in [3.2.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.0). Thanks for reporting!
