### ISSUE TITLE
When Saving Measures ordering of Roles and Perspectives are not maintained causing Git change detection.

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#341]
Hi,

Working in a folder Data Model against a Power BI Premium Workspace Database.

Every time I save a change there are always changes made to the Roles & Perspectives, the ordering flip-flops all the time even when no change has bee made to the Roles or Perspectives, it's just changing the order.

i.e.

**Perspectives**

<img width="461" alt="image" src="https://user-images.githubusercontent.com/362244/148809453-fb54a638-c5b3-44b9-82b1-dd572c8c3d8a.png">

**Roles**

<img width="568" alt="image" src="https://user-images.githubusercontent.com/362244/148808963-3c4653d8-2c8b-438f-8b0d-5015daf8bfe0.png">

Regards

Toby.

**Comment by otykier** [comment]
Hi Toby,
This happens because Analysis Services changes the ordering (and metadata is loaded from Analysis Services after the workspace database is deployed, to make sure TE3 is 100% in sync with the AS model).

To avoid the Git merge conflicts, use these folder serialization options (**Model > Serialization options...** menu for a specific model, or **Tools > Preferences > File Formats > Save-to-folder** for the default settings):

<img width="336" alt="image" src="https://user-images.githubusercontent.com/8976200/148900414-e851e486-4390-427b-8ec9-2097076654c9.png">

**Comment by tobimax** [comment]
Thanks,

I tried this, the only property difference was to enable inferred objects. That didn't help, as soon as you open the PBI Data Model from folder (with workspace DB) and save the model it creates a change in the folder that has just swapped around the ordering of the role permissions. It seems that there is no consistent order that the data model sends the object to TE3. Could the solution be to internally sort the tablePermissions node alphabetically. That way the JSON would be consistent regardless of the data model.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/362244/149949818-de21c03d-0601-46bd-8474-43f56752261f.png">

**Comment by otykier** [comment]
[3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1) now introduces a new option under **Tools > Preferences > File Formats**, which will sort the Perspectives and Roles arrays before saving to disk. You can also change this for an existing file under **Model > Serialization options...**:

![image](https://user-images.githubusercontent.com/8976200/151533727-f26a48ed-6413-4b46-a9ae-bf16854b578a.png)

Note this setting is OFF by default.

**Comment by tobimax** [comment]
Superb - Thanks Daniel.
