### ISSUE TITLE
Save as .pbit

### ISSUE THREAD

**Issue by gavingc** [TabularEditor/TabularEditor3#348]
Discussion for the possibility of enhancement, for saving TE created tabular models to .pbit files.

**Benefits**
This support would allow saving any model open in TE to a .pbit file.
The .pbit file can be opened in Power BI Desktop and ultimately recovered to .pbix.
Adds ability to accelerate model creation (scripting etc) and then move to .pbix for users that are more comfortable using Power BI Desktop.
Reduces vendor/product lock-in (to TE) and subsequent skittish IT department reluctance to approve the widespread use of TE.

**Assumptions**
Given that opening, editting and saving to .pbit is an existing feature, it is assumed there is already the framework for saving as .pbit.

**Work Arounds**
A known work around is to publish the tabular model to the Power BI service, in a workspace that is part of a development pipeline.
Then deploy the dataset to another workspace via the pipeline, then at the time of writing this work around a .pbix was able to be successfully downloaded (most likely unsupported functionality).
This .pbix may be recovered by (it initially opens a bit broken), and after a bit of mucking around and restarting Power BI Desktop a few times.

**Comment by otykier** [comment]
While we would definitely love to provide this capability, there is no supported way for us to do this at the moment, since Microsoft has not made any APIs publicly available, for saving model metadata as a .pbit file from scratch.

The reason why TE supports opening existing .pbit files, is that it is a relatively simple process (albeit unsupported by Microsoft) of simply unzipping the .pbit and extracting the ModelSchema json file from within, which contains the model metadata in a format that can be loaded by the TOM API. When changes are made, we just use the TOM API to save these back to the ModelSchema json file, zipping it back into the .pbit. However, the .pbit contains other stuff in addition to the ModelSchema json file, which is why we can't create it from scratch (unless Microsoft provides an API for that as well).

**Comment by gavingc** [comment]
Ah, what's needed is a Skeleton.pbit file.

Opening a model in TE, and then opening the Skeleton.pbit file in another TE window allows all the objects to be copied across, finally Save As "Skeleton Saved with New Table.pbit".
Examples attached (as .zip to work-around GitHub upload limitations, simply rename and remove .zip).

Also successfully tested with a more complex model (parameters, calculated tables, import & direct query partitions, measures).

The only speed bump was that copying and pasting tables resulted in some table partitions having 'Default' mode, setting to 'Import' or 'Direct Query' before saving the .pbit solved this.
[Skeleton.pbit.zip](https://github.com/TabularEditor/TabularEditor3/files/7955554/Skeleton.pbit.zip)
[Skeleton Saved with New Table.pbit.zip](https://github.com/TabularEditor/TabularEditor3/files/7955557/Skeleton.Saved.with.New.Table.pbit.zip)

**Comment by otykier** [comment]
Hi @gavingc
It's great that you've found a solution that works for you, but unfortunately we can't provide such functionality as a built-in feature in Tabular Editor, since there are no guarantees that it will work in all cases, as long as [editing .pbit files is unsupported territory](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-limitations) from Microsoft's point of view. If this limitation is ever lifted, we will definitely have full support for .pbit editing and creation with TE.

**Comment by gavingc** [comment]
Yes, understand.

At least the known future options, limitations, and work-arounds are documented now.

Two other modellers in my organisation are already finding uses for the Skeleton.pbit method.
