### ISSUE TITLE
Dependency Tree not updating (not fixed in 3.2.1)

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#401]
Hi @otykier can you please open this issue back up. Working on cleaning up calculated columns again today and with 3.2.1 the dependency view isn't updating. I have to close/reopen T/E to reflect changes in calc columns. The DAX is visible and fine, just appears to be the dependency tree.

-------------------------------------
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!

_Originally posted by @otykier in https://github.com/TabularEditor/TabularEditor3/issues/364#issuecomment-1024094027_

**Comment by otykier** [comment]
Hi @edhans 
Just to confirm, are you making a change to the DAX of a calc column through PBI Desktop? After making the change, does TE3 show the updated DAX on the column, but not the updated dependency tree? What happens if you use the File > Revert option or open the model again (File > Open > From DB…)? (Just trying to find a workaround so at least you don’t have to restart TE3)

**Comment by edhans** [comment]
Ok, a few notes:

1. using Revert doesn't work
2. Opening the model again does work, but that also resets all views, so Pivot Grids, debugging, etc. all gone, so it is only slightly faster than closing/restarting T/E.
3. Even deleted columns continue to show in the Dependency view even though it is not in the TOM explorer.

**Comment by otykier** [comment]
Thanks @edhans - we'll look into it.

**Comment by otykier** [comment]
Hi @edhans. We believe we've found the root cause of the issue, thanks to your description. [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2).
