### ISSUE TITLE
Delta Lake tables in Azure Data Lake Gen2

### ISSUE THREAD

**Issue by philip-charbonneau** [TabularEditor/TabularEditor3#403]
When pointing TE3 at a tabular model with delta lake tables  (that use the connector from https://github.com/delta-io/connectors/tree/master/powerbi), addition/changes to the existing delta lake tables results in errors.  

For example, if I try to create a copy of one of the tables, I get the error "the relationship for 'Variation' must be defined for the current table".  If I try to enable the refresh policy on a table, I get the error "m engine error token literal expected".  

As a work around, I make changes to the delta lake tables only in Power BI and any other changes are done with TE3.

Any suggestions on how I can get Delta Lake tables to work in TE3?  Is there another connector I should be using?

Thank you.

**Comment by otykier** [comment]
Are you using auto date/time on your model? In general, models that use auto date/time tables do not work very well with TE3, since Power BI creates these hidden calendar tables for every DateTime column in the model. This is typically the cause of the "relationship for 'Variation' must be defined" error.

Regarding the refresh policy error, when exactly does that arise? It seems unrelated to the other error. Could you provide a step-by-step example on this?
