### ISSUE TITLE
Problem during deployment,

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#417]
Dear community,

I would like to overwrite an already published model and now I get the following error:

![image](https://user-images.githubusercontent.com/49725984/153167435-8baaa930-878c-49c9-a663-d74a2708e826.png)

However, if I republish the data model under a different name, everything fits again.

What can I do?

Thank you Steffen

**Comment by otykier** [comment]
Hi Steffen,
This error originates from Analysis Services. Consider reporting the issue to Microsoft. They may be able to help if you provide a repro (for example the CreateOrReplace TMSL script generated by Tabular Editor's Deployment Wizard).

**Comment by Stewwe1** [comment]
Thank you, where can I find this TMSL script? :-)

**Comment by otykier** [comment]
Click the "TMSL script" button on the last page of the Deployment Wizard:

![image](https://user-images.githubusercontent.com/8976200/153176425-8b7b3c78-2794-48eb-b17e-14af828b516e.png)

(This is the script that Tabular Editor will execute against SSAS / Azure AS / Power BI, in order to deploy your model changes).

**Comment by Stewwe1** [comment]
Thank you very much Daniel
