### ISSUE TITLE
Is there a way to compile a C# script and run it in TE3 without having to provide source code?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#434]
I have a C# routine that I currently execute via TE3 scripting. I am looking to see if I can "compile" the script and still be able to execute it in TE3. Is this possible?

**Comment by otykier** [comment]
You can [save a script as a macro](https://docs.tabulareditor.com/onboarding/cs-scripts-and-macros.html#saving-a-script-as-a-macro). Is this what you had in mind?

**Comment by dpesante** [comment]
Well.. probably not… Basically, I do not want the person running the script to see the source code…. I believe that with the macro approach, the person running TE3 will be able to see the C# code that we wrote.

Basically, we are launching a product that leverages TE3 but we want to protect our intellectual property (the C# code).

Is there a way to do this?

**Comment by otykier** [comment]
Yes, macros are stored as clear text.

While it is possible to compile your code into a DLL that you can then call into from another script, this does not prevent a person from decompiling the DLL back to the original source. That goes for all compiled code, really. That’s why EULAs have clauses stating that users are not allowed to decompile the binaries, since there’s no technical way of preventing them from doing it.

**Comment by dpesante** [comment]
ok.. thanks... I am ok with that .. it is more to keep the "normal" user from looking at the code... It is also more presentable that way..

I am not a C# programmer, is there an article that shows both how to compile my current C# TE3 script into a DLL and how to call it from within TE3?

If you guys still offering 1/2 hr consulting sessions, I would like to schedule one to go over this in more details if possible.  I went to the link you provided a while back and it did not work.

**Comment by otykier** [comment]
We haven't documented it, since it is currently a moving target, but @bernatagulloesbrina has made some [really nice blog posts](https://www.esbrina-ba.com/bringing-tabular-editor-c-scripts-to-the-next-level/) if you want to learn more.

Regarding consulting sessions, please reach out to sales@tabulareditor.com. We'll look into the broken link.
