### ISSUE TITLE
Added support for Query Groups (aka. Power Query "folders") on partitions and named expressions

### ISSUE THREAD

**Issue by samaguire** [TabularEditor/TabularEditor3#435]
Is there an example of what this does? I can't seem to get it show folders and feel I've missed something here.

Thanks in advance.

**Comment by otykier** [comment]
Hi Sam,
We don't currently visualize the query groups as folders in the TOM Explorer (as we do for display folders on measures, columns, etc.), since objects with Power Query expressions are located in two different places within the TOM:

- Queries that are loaded into tables appear as a **partition** on the table
- Queries that are not loaded appear as **named expressions** on the model

Tabular Editor was designed with TOM in mind, so we visualize objects the same way as they appear in the TOM.

The Power Query Editor in Power BI, however, does not distinguish between queries that have been loaded and those that haven't. For example, you could have the following grouping in the Power Query Editor:

![image](https://user-images.githubusercontent.com/8976200/154915120-7d0eeb7a-c1c4-4fd5-9f2b-b2765c56d09f.png)

In Tabular Editor, this is what you'd see:

![image](https://user-images.githubusercontent.com/8976200/154915321-ca8f11b2-263b-470e-be46-6b47d38fbbf8.png)

So the only place we currently expose the query groups in TE, is in the partition/named expression properties:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8976200/154916337-98dcd1ee-6926-4c3e-a350-8c1193346c54.png">

The groups themselves can be edited through the Model object properties:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/8976200/154916432-a1f6a6f1-2f41-4d07-a1fb-c927820962a6.png">

**Comment by samaguire** [comment]
Aha! Cool thanks. I’ve enabled unsupported pbix features and that’s now appeared 😊


Regards,
Stephen
