### ISSUE TITLE
[TE 3.2.2] Sorting a table preview on more than one column doesn't work

### ISSUE THREAD

**Issue by eybert** [TabularEditor/TabularEditor3#445]
When you Shift+Click on a column header in Table Preview to sort on a second column, a sorting indicator appears. However, the column is not sorted accordingly.

**Comment by otykier** [comment]
Hi @eybert 
Thanks for reporting. Unfortunately, we can't sort a table preview by multiple columns since this is not supported by the TOPNSKIP function (at least not if we want to be able to "skip" a number of rows):

![image](https://user-images.githubusercontent.com/8976200/155950481-af1f2383-bc61-452b-8373-0b292986a20d.png)

So the bug in this case, is that the column headers seem to allow sorting by multiple columns (either by Shift+Click'ing as you wrote, or by right-clicking and choosing "Sort Ascending/Descending). We will make sure to fix this to avoid the confusion.

**Comment by otykier** [comment]
Fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks for reporting!
