### ISSUE TITLE
DAX Editor Auto-complete Settings

### ISSUE THREAD

**Issue by GMedlin** [TabularEditor/TabularEditor3#459]
I may just be missing something in my tweaking the preferences for the DAX Editor, but there are a couple of things in particular I'm having trouble getting used to, coming from PBI Desktop. I'd like to be able to tweak how this is handled a little more specifically without turning off auto-complete entirely.

1. Auto-complete is always putting () for functions, which is fine if creating something brand new, but if you already had a function typed out and are experimenting or replacing it with a different one, auto-complete wipes out your existing function's parameters. In these situations, I'm holding shift and typing out the name myself. Personally, I prefer PBI Desktop's & Excel's handling of this by only giving you the left parenthesis.

2. Auto-complete popping up after typing a space, which I like a lot of times, but it's rarely helpful to me for it to pop-up after an equal sign like VAR name = . I usually want to start a new line, so I have to hit ESC or remember to not type a space after the = to use enter to go to a new line uninterrupted.

**Comment by samaguire** [comment]
For point 2, have you tried pressing enter straight after the '=' instead of space? (Since you know you're going to move to a new line it doesn't make sense to add a space...)

I agree with you on point 1 - that made it tricky for me as well initially. An option here would be great.

**Comment by GMedlin** [comment]
> For point 2, have you tried pressing enter straight after the '=' instead of space? (Since you know you're going to move to a new line it doesn't make sense to add a space...)
> 
> I agree with you on point 1 - that made it tricky for me as well initially. An option here would be great.

Yep! That's what I've been trying to make a habit. Hard habit to break ;)

**Comment by otykier** [comment]
Great suggestions.
I also agree with point 1. I'm not even sure it needs to be an option, since the only scenario in which you would invoke autocomplete on a function while the character following the cursor is an opening parenthesis, is indeed when you're replacing one function with another.

Regarding point 2, I agree that the autocomplete is a bit too aggressive at times. I think we will add an option here, something like "After entering a letter character", which will help tone it down.

![image](https://user-images.githubusercontent.com/8976200/158162148-4b7a276a-ead5-4860-ba2f-dcf4b74a28e7.png)

**Comment by otykier** [comment]
In [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3) we've added an option to make auto-complete less aggressive (i.e. only popping up when a letter is entered): 

![image](https://user-images.githubusercontent.com/8976200/162145374-8235bc69-4857-4d8b-b53d-abeb12a9c4fb.png)

We've also fixed the issues with parentheses when replacing a function with another.
