### ISSUE TITLE
Dependent objects which do not exist in the model

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#491]
Is there a way to use the DAX parser/lexer to identify objects (columns/measures/tables) which are referenced in DAX (measures, calculated columns, calculated tables, calculation groups) which do not exist in the model? The DependsOn method only identifies objects which do exist in the model. This could be a handy BPA rule :)

Thanks!

**Comment by otykier** [comment]
Hi Michael,

I'm not sure I understand this request. The "Messages" view in TE3 should already show you when a DAX expression has invalid object references.

Keep in mind that the DAX parser is not available in TE2, so creating a BPA rule that relies on this, is probably not a good idea. Using the lexer alone will be very difficult, since you need to be aware about active row contexts. For example, in an expression such as:

```dax
SUMX(Product, [List Price])
```

`[List Price]` looks like a measure reference, but if there's a column on `Product` with that name, then the above is perfectly valid DAX.

**Comment by m-kovalsky** [comment]
You are absolutely correct. This is a fantastic feature in TE3! This type of rule is perfect for your DAX parser.
