### ISSUE TITLE
LASTNONBLANK doesn’t show up in intellisense?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#509]
Anyone else see this? If I type **CALCULATE(LAST** in the expression editor (3.2.3) I only get LASTNONBLANKVALUE and misc suggestions. If I just type **LAST** it shows up, but not if it is part of a larger expression.

**Comment by otykier** [comment]
Hi @edhans.
I am not sure if this is a bug or a 'feature'. Let me explain:

[`LASTNONBLANK`](https://dax.guide/lastnonblank/) returns a 1-column and 1-row table result, where as [`LASTNONBLANKVALUE`](https://dax.guide/lastnonblankvalue/) returns a scalar value. We've designed TE3's IntelliSense to only suggest functions that return a scalar value, whenever it pops up on a function argument that is expected to be scalar, such as the 1st argument of CALCULATE. You can test this by typing `COUNTROWS(LAST`, in which case the IntelliSense should suggest `LASTNONBLANK` and not `LASTNONBLANKVALUE`.

In DAX, 1-column and 1-row table results are implicitly converted to scalar values, which is why `CALCULATE(LASTNONBLANK(..., ...))` is perfectly valid DAX, but I'm guessing there's a reason why `LASTNONBLANKVALUE` exists, so it is probably the recommended choice.

Maybe @marcosqlbi has an opinion about that?

**Comment by marcosqlbi** [comment]
If you write CALCULATE(LASTNONBLANK('Date'[Date])) you should really write CALCULATE(MAX('Date'[Date])) because otherwise what you are really writing is CALCULATE(MAXX(CALCULATETABLE(DISTINCT('Date'[Date])),'Date'[Date])) and there are no reasons to do that.

**Comment by edhans** [comment]
Marco, thanks. I will need to look again at my code. I wasn’t using CALCULATE() for LASTBLANK, but because I needed to alter the crossfilter direction in the model for this particular variable in a measure. But I’ll play with it monday when back on that laptop and see if MAX will work.

Thanks too Daniel for alerting me that LASTBLANK returns a table, not a scalar value. I was not aware of that.
