### ISSUE TITLE
Option to sort a column with another one hidden ?

### ISSUE THREAD

**Issue by PalombieChamonix** [TabularEditor/TabularEditor3#590]
The option to sort a column with another column is not visible.
![image](https://user-images.githubusercontent.com/91263359/176849766-d866c85c-585c-46f8-8467-48c42509ebae.png)

**Comment by otykier** [comment]
Hi @PalombieChamonix 
Many column properties are not available for editing in Tabular Editor when connected directly to a Power BI Desktop model, due to the [limitations described here](https://docs.tabulareditor.com/te3/desktop-limitations.html). The article describes how you can enable *unsupported* modelling operations, if you want to access all object properties.
