### ISSUE TITLE
Is the ability to create/update calculated tables in TE3 C# scripting close to being a reality on PBI desktop?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#613]
I recently downloaded a copy of Bravo and noticed they have an option to create/update their generated calendars which are basically calculated tables. I was under the impression this was not allowed when running desktop. Is there a way to now do this in TE3?

**Comment by otykier** [comment]
Adding calculated tables through Tabular Editor was always a possibility, but you have to enable unsupported modelling operations (in TE2 it's under File > Preferences, in TE3 it's Tools > Preferences), since Microsoft [explicitly does not support addition/editing of tables](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations) through 3rd party tools. I guess the Bravo team tested it thouroughly and felt confident that it wouldn't hurt - TE3, being a commercial tool, we have to stick to what is officially supported by default.
