### ISSUE TITLE
No error sign for Evaluation Error in calculated columns 

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#682]
![image](https://user-images.githubusercontent.com/74975641/193272802-ff95b2b5-1ac3-42ea-a9ff-cd6a997048fb.png)

**Comment by otykier** [comment]
What does the DAX expression on your calc column look like? Does TE show an error when editing its DAX expression?

**Comment by MarioMue13** [comment]
Correct:
VAR vMaxCreationDate =
    CALCULATE(
        MAX( v_FactSalesOrderLines[CreationDate] ),
        ALL( v_FactSalesOrderLines )
    )
RETURN
    IF(
        v_DimDate[Period]
            = YEAR( vMaxCreationDate ) * 100
                + MONTH( vMaxCreationDate ),
        "Current Period",
        v_DimDate[MonthYear]
    )

Wrong:
VAR vMaxPeriod =
    CALCULATE(
        MAX( v_FactSalesOrderLines[CreationDate] ),
        ALL( v_FactSalesOrderLines )
    )
RETURN
    IF(
        v_DimDate[Period] = CONVERT( LEFT( vMaxPeriod, 6 ), INTEGER ),
        "Current Period",
        v_DimDate[MonthYear]
    )

In the wrong version a Date is compared with an Integer. No Error except the info in the screenshot

**Comment by otykier** [comment]
I see. The problem in this case, is that your DAX code is perfectly valid.

The `CONVERT` function can not determine in advance, whether it is going to fail or not - this depends entirely on the data that you put in.

For example, consider a table containing a single column with the following strings:

| Value |
| --- |
| 123 |
| Abc |

Now imagine you add a calculated column with the following DAX: `CONVERT(Table[Value], INTEGER)`

This DAX is perfectly valid, but the conversion will fail for some of the rows in this table, e.g. when [Value] = "Abc". However, a calculated column must either succeed for all rows in the table, or it will fail entirely. To deal with this, you could wrap the DAX on the calculated column with a call to `IFERROR(...)`

But the main point is that Tabular Editor cannot know whether the expression wil fail or not, since this depends on the content of the table.
