### ISSUE TITLE
Pivot table KO

### ISSUE THREAD

**Issue by PalombieChamonix** [TabularEditor/TabularEditor3#717]
The pivot table is crashing all the time, espicially since the last releaser of TE 3. When draging the second item, TE is freezing. Impossible to go further. And TE must be killed via the task manager

**Comment by otykier** [comment]
@PalombieChamonix a few users have reported this issue, but so far we haven’t been able to reproduce this. Any chance you can send a recording where you show this happen consistently?

As a workaround, instead of dragging an item over to the pivot, you can right-click on it and use the menu options to add it to the pivot instead.

**Comment by otykier** [comment]
This bug should now be fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html?tabs=downloads). Please let us know if it resurfaces.
