### ISSUE TITLE
Expression editor sometimes empty unless I click on its header

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#739]
TE3: cannot reproduce this consistently, but sometimes I have to click on the Expression Editor header to see an expression, otherwise it appears empty.

**Comment by mlonsk** [comment]
This happens to me under the following circumstances:
I open TE3 through External Tools in PowerBI.
The expression editor is open along with the TOM Explorer of the model, but the editor is grey.
I choose a measure in the TOM Explorer, and the expression editor is still grey, and I have to then click on the expression editor header before seing the expression of the measure selected. 

Expected behaviour:
When I select the measure the expression editor as the only open window should show me the expression of the measure.

**Comment by zenzeinet** [comment]
Yes, that happens to me too, except that I launch TE3 manually, not through External Tools

**Comment by otykier** [comment]
Hi all. I haven't been able to reproduce this. Any screen capture or additional details you could share would be appreciated. Thanks!

**Comment by mlonsk** [comment]
In 3.4.0 I do not see the issue either. 
@zenzeinet Are you still experiencing this problem?

**Comment by mlonsk** [comment]
Hi @zenzeinet 
Thank you for the video, we have been able to reproduce the bug and will look to fix it in a future update.

**Comment by otykier** [comment]
This is now fixed in [3.4.1](https://docs.tabulareditor.com/te3/other/release-notes/3_4_1.html?tabs=downloads). Thanks for reporting!
