### ISSUE TITLE
Setting Non-US Dates

### ISSUE THREAD

**Issue by Kealkil4** [TabularEditor/TabularEditor3#75]
I am in Europe - DD/MM/YYYY dates.

I was getting a warning that my Datekey was not formatted correctly, even though it was.  I figured out where to change the rule for the Date Validation.

However, for a column which genuinely did not have a Date Format, I ran the "Generate fix script" and this was suggesting MM/DD/YYYY format.

Where do I go to fix this bit?

It doesn't appear to be picking up and applying my Locale.

**Comment by otykier** [comment]
Are you talking about a Best Practice Analyzer warning? In that case, the fix script is defined within the Best Practice rule itself. These rules do not ship with Tabular Editor. Instead, the rules may be defined inside the model you're working with, or you may have loaded them from somewhere else. If so, please contact the author of the rules that you are using.

**Comment by Kealkil4** [comment]
Yes it was a Best Practice Analyzer Warning.
 
I had only latterly started using the Tabular Editor 2 and I did download the Best Practice Analyzer script as advised by Patrick – Guy in a Cube.
 
I downloaded Tabular Editor 3 yesterday.
So I am looking at the same Data Model (to which the Best Practice rules had already been applied using TE2).
 
I didn’t load anything explicitly into TE3 … but the Best Practice Analzser Tab is there right next to the TOM explorer.
Incidentally, I cannot find where the Advanced Scripting Window is in TE3 (if such exists?) to re-apply the Best Practice rules.

**Comment by otykier** [comment]
Sounds like the script provided by Patrick includes the rule that has the US-based date format. You should probably reach out to him to let him know that the rules are not good for non-US users :)

Anyway, you can manage all of your Best Practice Rules in Tabular Editor 3 by clicking on the "Manage rules" button on the Best Practice Analyzer tab.

![image](https://user-images.githubusercontent.com/8976200/121527782-1159bc80-c9fb-11eb-845e-a93786f1f9ff.png)

Locate the rule and either disable it or edit it to work with non-US based date formats. Currently, you can't change the "FixExpression" of the rule through Tabular Editor, but you can do that if you open the rule definition file (`%localappdata%\TabularEditor\BPARules.json`) in a text editor. Since I'm not sure exactly what rule you're referring to, it's difficult for me to assist much further.

**Comment by otykier** [comment]
@Kealkil4 did you get the answer you needed? Can we close this issue?

**Comment by Kealkil4** [comment]
I have been too busy for the past week to look at the issue, but I think there was enough in the original reply for me to chase down the issue.So yes you can close it.  If I fail to resolve, I will raise my hand again.Tabular Editor is some product. I regret I did not pick up on it earlier.TedSent from my Huawei phone-------- Original message --------From: Daniel Otykier ***@***.***>Date: Fri 25 Jun 2021, 10:02To: TabularEditor/TabularEditor3 ***@***.***>Cc: Kealkil4 ***@***.***>, Mention ***@***.***>Subject: Re: [TabularEditor/TabularEditor3] Setting Non-US Dates (#75)
@Kealkil4 did you get the answer you needed? Can we close this issue?
