### ISSUE TITLE
Table Preview - Filtering Date Fields - Odd Selection of Filters

### ISSUE THREAD

**Issue by rminder** [TabularEditor/TabularEditor3#77]
When I preview data from a table and filter on a date field I see a rather odd set of filter criteria and none of the criteria I would expect to see. For example, I see "Beyond this year", "Earlier this week", "Later this week" etc. While these are interesting, I don't see the ones I would expect to see, such as:

- Less than or equal to
- Greater than or equal to
- Between two dates
- Custom

What's a little inconsistent is that I do see these if I filter on a numeric column. Can we get the standard filters added for date fields. Or, perhaps are they there and I am missing them?

**Comment by otykier** [comment]
Fixed in [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6). Thanks for reporting!

![image](https://user-images.githubusercontent.com/8976200/122367071-67c77d80-cf5c-11eb-954b-44938095158d.png)
![image](https://user-images.githubusercontent.com/8976200/122367008-5c745200-cf5c-11eb-87c1-bd040857f457.png)
![image](https://user-images.githubusercontent.com/8976200/122366942-50889000-cf5c-11eb-8078-ef8af258e535.png)
![image](https://user-images.githubusercontent.com/8976200/122366970-567e7100-cf5c-11eb-94d8-3703685ae79f.png)
