### ISSUE TITLE
view toolbars issue - dax query

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor3#783]
1. View -> Toolbars -> C# script (select)
2. View -> Toolbars -> DAX Query (select)
3. View -> Toolbars -> DAX Query (unselect)

If you go through this protocol, the DAX Query buttons have been removed it leaves a large gap between the standard toolbar buttons and the C# script buttons.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/29556918/210224773-7a3df8b8-fb30-42dc-a6de-6efb070d3972.png">

**Comment by otykier** [comment]
This is by design, as we do not modify toolbar positions when a toolbar is manually hidden (like in the steps you outline). The gap should disappear as soon as you change the context (i.e. focus the TOM Explorer, and then go back to the Expression Editor). Note, you can also move toolbars around manually by unchecking **Lock menus and toolbars** under **Tools > Customize > Options**.
