### ISSUE TITLE
Need help finding group by columns field

### ISSUE THREAD

**Issue by ThorPlees** [TabularEditor/TabularEditor3#793]
I followed this tutorial: https://p3adaptive.com/2022/05/completing-the-set-up-field-parameters-using-tabular-editor/

And there it says I need to set group by columns to a value. But when I open up my tabular editor then I don't have that field. 
How can i get that field?

**Comment by mlonsk** [comment]
Hi @ThorPlees 
Could you provide a bit more information such as which type of model are you opening (PBI Desktop, PPU, Premium Capacity) and how far in the process of creating a Field parameter have you come.
Alternatively you can use the script that Daniel provided here to create field parameters: https://github.com/TabularEditor/TabularEditor3/issues/541#issuecomment-1129228481

If you are using Tabular Editor by opening it has an External Tool to Power BI Desktop, you may to enable "Unsurported modeling features" in Preferences in order to see the field in the columns properties. 
<img width="353" alt="Screenshot_20230111_153956" src="https://user-images.githubusercontent.com/11939114/211843684-e2abe6c7-44a0-43cc-91c9-4aff7be3bdf1.png">

**Comment by ThorPlees** [comment]
Hello @mlonsk  and thanks for your reply.

I'm using analysis service. I could do all the steps of that tutorial but cant do the group by column field as i don't have it. 
If i understand correctly i cant do field parameter with analysis service. When using the script it gives error, as once again i don't have that group by columns field and that script tries to set value to it.
If i opened TabularEditor from power bi desktop, then i was able to create field parameter.

**Comment by mlonsk** [comment]
Hi @ThorPlees 
Yes, that would be the reason. Field parameters are only available in Power BI, to my knowledge.
Microsoft documentation says that the only way to use Field Parameters with a live connection is to enable Direct Query for AS, create a local model in Power BI with the field parameter therein: 
https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters#limitations

**Comment by edhans** [comment]
FWIW, that article was written assuming you are using the XMLA endpoint, not Power BI Desktop, where you can create field parameters much more easily. You have to have write permissions, and you have to be in Read/Write mode for the dataset or that field may not show up.

**Comment by mlonsk** [comment]
Great input @edhans 
thank you
