### ISSUE TITLE
Cannot edit measures/custom columns in Tabular Editor

### ISSUE THREAD

**Issue by vgeldbr** [TabularEditor/TabularEditor3#825]
Using build3.4.8392.26581 against Power BI desktop Version: 2.112.1161.0 64-bit (December 2022). I've not used it for a while but I am now unable to edit measures in Tabular Editor. I can see the measure expression but nothing happens when I type in the windows.  I've tried many times including restarting both Powere BI desktop and Tabular Editor. I am able to create new measures.

**Comment by otykier** [comment]
Apologies for the late reply (for TE3 questions, please make sure to post the issues [here](https://github.com/TabularEditor/TabularEditor3/issues/825)).

Did you get a warning when opening the model in Tabular Editor? What happens if you enable **Allow unsupported modeling operations** under **Tools > Preferences**.

Note the limitations for Power BI external tools: https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations

**Comment by DBojsen** [comment]
Hi @vgeldbr 

Since we haven't received any reply to this issue, we'll go ahead and close it.
You are welcome to reopen with more info or create a new, if needed in the future.

BR David - TE Support
