### ISSUE TITLE
Date dd/mm/yyyy or dd/MM/yyyy

### ISSUE THREAD

**Issue by l33smyth** [TabularEditor/TabularEditor3#86]
Hi
This could be a setting I've missed somewhere but the standard Format String selections appear to be at odds with the standard in Power BI Desktop when it comes to dates, certainly the non-US dates at least.  In TE3, "dd/mm/yyyy" is only possible as a custom format, but in Desktop, this is a standard selection; choosing the TE3 option of "dd/MM/yyyy" is regarded by PBI Desktop to be a custom format.  Both ways appear okay when dragged on to a report page, so this isn't a very severe bug - just an irritation!

![image](https://user-images.githubusercontent.com/78022740/122102840-ca5e3380-ce0d-11eb-8e80-1d66163e9f2b.png)

**Comment by dgosbell** [comment]
This is due to a difference in the way that DAX and c# format strings work (TE3 is written in c#)

| C# | DAX | Description |
| --- | ---| --- |
| mm | nn | Minutes |
| MM | mm / MM | Months|

in C# the uppercase `M` is different to the lowercase `m` so TE3 probably needs to translate these when generating the examples. I'd stick with "dd/mm/yyyy" and put up with the incorrect example until this gets fixed.

**Comment by otykier** [comment]
Fixed in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8). Thanks for reporting!
