### ISSUE TITLE
Columns not showing up on the table in Tab Editor 3 where as it does on 2 

### ISSUE THREAD

**Issue by creedrulz** [TabularEditor/TabularEditor3#88]
too many issues with Editor 3 

Issue -1 No columns showing up 
![image](https://user-images.githubusercontent.com/86038751/122344612-8f790e80-cf79-11eb-949f-f055c6886d78.png)

issue- 2 no error on Power or Editor 2 but on 3 throwing an error 
![image](https://user-images.githubusercontent.com/86038751/122345380-6016d180-cf7a-11eb-8a71-42ce9b9f9c99.png)

**Comment by otykier** [comment]
Issue 1: You can select/deselect which types of objects to show just above the TOM Explorer - similar to Tabular Editor 2. In your screenshot, you have deselected columns:
![image](https://user-images.githubusercontent.com/8976200/122346355-27aacf80-cf49-11eb-8160-caa863026925.png)

Issue 2: This is not an error but a warning, because you're not following the best practice (which is to ALWAYS fully qualify all column references).

**Comment by creedrulz** [comment]
Thanks it for your help . I thought it was a bug

**Comment by creedrulz** [comment]
Not sure why it doesn't allow me to edit the expression .

![image](https://user-images.githubusercontent.com/86038751/122347932-2c897680-cf7d-11eb-8935-b012f62e0578.png)

**Comment by otykier** [comment]
Looks like you're working against a Power BI Desktop model. Tabular Editor limits the operations you can perform on such a model, to [those supported by Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations). Editing a calculated table expression through an external tool is not currently supported by Power BI Desktop.

If you want to experiment, there is an option under "Tools > Preferences > Allow unsupported modelling operations", which will unlock all properties for editing, included Calculated Table expressions, but **please be aware that this could potentially break your .pbix file**, so keep a backup of the file just in case.

**Comment by otykier** [comment]
@creedrulz are you unblocked? Can we close this issue?
