### ISSUE TITLE
Have the TOM refresh if it recognizes a partition no longer exists.

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#888]
I was refreshing some historical partitions after a full refresh and had TE open while the full refresh was being done. The service deleted 
2202Q102 as it had moved beyond the historical range, but instead of TE recognizing that, it gave me this error and I had to manually refresh the TOM using the REVERT button. Not a huge issue, but a nice to have.

![image](https://user-images.githubusercontent.com/45298358/234716520-f5f0b103-036d-41e9-b807-fd5e46051b4d.png)

**Comment by DBojsen** [comment]
Hi @edhans 

When you are connected to a local PBI Desktop or SSAS, we will actively look for changes thru an AS trace,
but this is unfortunately not an option for remote models due to performance concerns.
So the experience you are seing is be design, and we unfortunately have no plan to change this.

BR David - TE3 Support
