### ISSUE TITLE
Is there a way to force a "Revert" and "Save" of the Model object changes in c# scripting?

### ISSUE THREAD

**Issue by dpesante** [TabularEditor/TabularEditor3#893]
Is there a way to force a "Revert" and "Save" of the Model object changes in c# scripting?

I tried: Model.ResetModifiedState(); but that did not work.

Is this doable?

**Comment by DBojsen** [comment]
Hi @dpesante 

Can I ask what you are trying to achieve?
If you want to have a try/catch approach in your scripts, you can just throw an Exception in the end - this will roll back any changes done in the script:

```
try
{
	Model.Tables["Orders"].Measures["Net Orders"].FormatString = "#,##000";
	throw new Exception("Error happening in script");
}
catch (Exception ex)
{
	if (ex.Message == "Error happening in script")
	{
		Info("I forced an error to make an example");
	}
	throw new Exception("Rolling back");
}

```

**Comment by dpesante** [comment]
@DBojsen thanks for the quick reply.

Here is what I am trying to do:
Use Case #1: I have an "interactive" c# script that helps the user create certain measures, etc. One of the options in the menu it to allow the user to "reset" the datamodel back to "undo" whatever changes they have done via the c# app (like an undo feature). Currently, the only way I have seen this work is for them to end the script (e.g. return) and then click on the TE3 button to "reload" the datamodel (where it gives you the warning that you are about to loose your changes). Since we are planning on turning my c# script into an external tool, I want to give the user the ability to do that via the menu's we provide. 

Use Case #2: Again, via the same menu, I would like to give the user a way to force a save of the data model with whatever changes they have made so far, check them out in the Power BI app, and then continue. All without exsiting the c# script.

In my old days, we used to call that "Transaction State" but not sure how this is done with the Model object.

Thoughts?

**Comment by dpesante** [comment]
@DBojsen I tried this:

try
{
	Model.Tables["Orders"].Measures["Net Orders"].FormatString = "#,##000";
	throw new Exception("Error happening in script");
}
catch (Exception ex)
{
	if (ex.Message == "Error happening in script")
	{
		Info("I forced an error to make an example");
	}
	throw new Exception("Rolling back");
}

But the script ends when the "Rolling Back exception happens... I need the script to stay running so that they user can pick a new option when after they roll back...

**Comment by otykier** [comment]
Hi @dpesante 
You mentioned that you have plans to create your own external tool to encapsulate the features of your script. In that case, you should consider creating a C# app from scratch using Visual Studio and the AMO/TOM client library, to directly access the `Model` object and other TOM objects. TOM lets you revert all local changes by calling [`Model.UndoLocalChanges()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.model.undolocalchanges?view=analysisservices-dotnet). It also lets you save all changes by calling [`Model.SaveChanges()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.model.savechanges?view=analysisservices-dotnet).

The TOMWrapper library used by Tabular Editor 3 is not suitable for this type of script, since it contains its own transaction/undo handling mechanism, which is consumed by Tabular Editor's UI, and is not designed for consumption through C# scripts. And in any case, you would not be able to use this in a standalone external tool, since the license terms for TE3 does not permit shipping TOMWrapper.dll (or other parts of the code) as part of 3rd party tools.

Here is an introduction on how to develop custom external tools for Power BI Desktop: https://www.powerbidevcamp.net/sessions/session31/
