### ISSUE TITLE
Exclude from Model Refresh Description - wrong text or wrong understanding on my part?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#906]
**Describe the issue**
I set the "Exclude from Model Refresh" setting to TRUE for a table we only want to refresh the first time a model refreshes, and never again, at least automatically. The description for this field says if the partition has been processed, it won't be refreshed. But in a fresh deployment via Deployment Pipelines, it _wouldn't_ be processed after the first promotion, correct, and so per this description it seems it should have been refreshed.
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/00d6250d-512a-4653-a968-59fb0ba19439)

It wasn't a huge deal, I just refreshed it when the full refresh was done. But now that I know how it works, I will refresh that table first after deploying to PROD so when the full refresh is done, the model will work. As it was, many visuals were broken because the relationships to that table had not been calculated on the model refresh.

** Which version are you currently using? **
Tabular Editor 3.7.1
Tabular Editor 3 edition: Enterprise

**Comment by otykier** [comment]
You should ask this question to the Analysis Services team. Tabular Editor just surfaces TOM properties and their descriptions: https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.table.excludefrommodelrefresh?view=analysisservices-dotnet

If you want full granular control over which tables get refreshed, consider refreshing using XMLA instead of using Power BI’s scheduled refresh or “refresh now” options.
