### ISSUE TITLE
DAX formatter and 'tablename'

### ISSUE THREAD

**Issue by smedv1** [TabularEditor/TabularEditor3#991]
If i use DAX-Formatter, then tablenames with '..' are removed
I have a status table with name status - as this is a reserved word, i have to write it with 'status'
when i use the DAX-Script function and the DAX-formatter symbol then 'status' is replaced with status, which results in an error in Power BI.

Tabular Editor 3, version: 3.10.1
Tabular Editor 3 edition: [Desktop]

**Comment by mlonsk** [comment]
Hi @smedv1 
Are you using the Script DAX feature when this happens or does it happen when you write the DAX Script yourself?

Per default Tabular Editor escapes the '..' when they are used in for example a table name. Thus the DAX Script will look like this:
![image](https://github.com/TabularEditor/TabularEditor3/assets/11939114/c2c3eda0-58c7-4922-916f-d28aa711667c)

Does this not happen for you?

**Comment by mlonsk** [comment]
Hi @smedv1 

This is a bug, thank you for reporting it. We will fix it in our next release.

**Comment by otykier** [comment]
Curse Microsoft for not properly documenting which names are reserved keywords :-(

**Comment by smedv1** [comment]
Ok, fine - by formatting with the dax formatter just leave the ' untouched, so don't have to deal with reserved keywords - but yes its annoying, that status seems to be an undocumented reserved word ;-)

**Comment by otykier** [comment]
It's a matter of ensuring consistent code style - that's why the built-in DAX formatter may change how tables are quoted. By default, the formatter will only quote table names when they are needed (reserved keywords, table names containing special characters or spaces, etc.). But if you enable **Always quote tables** under **Tools > Preferences > DAX Editor > Auto Formatting**, quotes will always be added.

![image](https://github.com/TabularEditor/TabularEditor3/assets/8976200/d5faa8b0-d0d2-442e-a9f5-a40c4e244bcc)

**Comment by otykier** [comment]
This is now fixed in [3.11.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.11.0). Thanks for reporting!
